# Generated by Django 3.0.6 on 2020-05-31 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200531_2116'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.CharField(choices=[('MORNING', '8-12'), ('AFTERNOON', '1-5')], default='MORNING', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='act_name',
            field=models.ForeignKey(db_column='name', default='', on_delete=django.db.models.deletion.CASCADE, related_name='nameR', to='page.Activity', to_field='name'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='child_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='register.Child'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentR', to=settings.AUTH_USER_MODEL),
        ),
    ]
