# Generated by Django 3.0.6 on 2020-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200531_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='act_time',
            field=models.CharField(choices=[('MORNING', '8-12'), ('AFTERNOON', '1-5')], default='', max_length=10),
        ),
    ]
