# Generated by Django 3.0.6 on 2020-05-31 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_appointment_act_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='act_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
