# Generated by Django 3.0.6 on 2020-06-01 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_appointment_act_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='act_name',
            new_name='activity_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='act_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='act_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='activity_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appointment',
            name='activity_time',
            field=models.CharField(choices=[('MORNING', '8am-12am'), ('AFTERNOON', '1pm-5pm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.CharField(choices=[('MORNING', '8am-12am'), ('AFTERNOON', '1pm-5pm')], default='MORNING', max_length=10),
        ),
    ]
