# Generated by Django 3.0.6 on 2020-05-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='child_condition',
            new_name='notes',
        ),
    ]
