# Generated by Django 3.0.6 on 2020-05-28 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0003_auto_20200528_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notes',
        ),
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
