# Generated by Django 3.0.6 on 2020-05-28 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0005_auto_20200528_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='user',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='child',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2083, null=True),
        ),
    ]
